from pathlib import Path
import nbformat as nbf

ROOT = Path(__file__).parents[1]
lessons = [
 ("01_instruction_contracts", "Instruction contracts: from vague request to behavioral specification", "A support leader asks: ‘Handle this customer.’ You will convert that ambiguous request into an auditable contract: objective, trusted context, constraints, output schema, and escalation rule.", "01_instruction_contracts.py", "What could a model do incorrectly if the term ‘handle’ is not defined? Add one measurable success criterion and rerun the lab."),
 ("02_structured_outputs", "Examples and structured outputs: build interfaces, not prose", "Northstar must route cases automatically. You will compare a prose answer with a typed `CaseBrief`, inspect schema validation, and design examples that clarify edge cases rather than merely repeat the happy path.", "02_structured_outputs.py", "Add a `priority` enum. Which malformed response should fail validation, and how should a bounded repair flow respond?"),
 ("03_context_engineering", "Context engineering: select evidence under a budget", "A support request arrives with policy, marketing copy, historical chat, and account state. You will select relevant, authoritative evidence and demonstrate why indiscriminately adding tokens can degrade a decision.", "03_context_engineering.py", "Add a stale policy candidate. What ranking metadata would prevent it from being selected?"),
 ("04_rag_and_tools", "RAG and tools: design evidence-first interfaces", "The copilot needs a refund policy. You will design a narrow lookup tool, attach evidence to the final case, and distinguish a tool result from trusted system instruction.", "04_rag_and_tools.py", "Add a tool error. Is it retryable, an escalation, or an abstention? Explain why."),
 ("05_multimodal_prompting", "Multimodal prompting: invoices, OCR, and visual provenance", "A customer submits an invoice screenshot. You will extract only visible facts, preserve a page-level citation, flag uncertainty, and keep a financial action behind human review.", "05_multimodal_prompting.py", "Reduce OCR confidence to 0.55. What changes in the output contract and escalation path?"),
 ("06_prompt_security", "Prompt security: untrusted content is data", "A retrieved runbook contains instructions to issue a refund. You will identify the indirect prompt injection, preserve it for audit, block the action, and explain the application-level controls a prompt cannot provide.", "06_prompt_security.py", "Create a second attack that attempts to exfiltrate customer data. List the controls at retrieval, tool, and output boundaries."),
 ("07_prompt_evaluation", "Evaluation: release prompts with evidence", "A new prompt looks impressive in a demo. You will run a small golden set, score task validity and grounding, inspect traces, and decide whether it clears a release gate.", "07_prompt_evaluation.py", "Add an ambiguous customer request and define expected abstention behavior. Which metric catches a confident but unsupported answer?"),
 ("08_agentic_prompts", "Agentic prompting: bounded loops and delegation contracts", "The copilot must investigate rather than answer immediately. You will implement a bounded evidence-gathering loop and define an agent contract with tool permissions, stop conditions, and escalation.", "08_agentic_prompts.py", "Force the lookup to return no evidence. How does the stopping rule avoid both hallucination and an infinite loop?"),
 ("09_promptops_capstone", "PromptOps capstone: model-aware prompts with release gates", "Northstar is ready to ship. You will compare prompt versions, review cost and groundedness, select a candidate only when it meets the release policy, and retain a rollback path.", "09_promptops_capstone.py", "Change the candidate cost above the budget. What should the deployment pipeline report, and which artifact enables rollback?"),
]

for index, title, scenario, lab, exercise in lessons:
    nb = nbf.v4.new_notebook()
    nb["metadata"] = {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python", "version": "3"}}
    nb.cells = [
      nbf.v4.new_markdown_cell(f"# {title}\n\n## Northstar Support Copilot\n\n{scenario}\n\n**Learning outcomes**\n\n- Explain the design choice and its trade-offs.\n- Run a credential-free implementation and inspect its evidence.\n- Diagnose a deliberate failure mode.\n- Record a testable rule before changing a production prompt."),
      nbf.v4.new_markdown_cell("## Mental model\n\nA production prompt is a contract between a system and a model. Keep **instructions** separate from **data**, make success observable, and place permission checks in application code. The general pipeline is:\n\n```text\nUser need → task contract → selected context → model/tool step → validation → answer or escalation\n```\n\nThe exact wording is model-dependent; the behavioral contract and evaluation criteria should remain stable."),
      nbf.v4.new_code_cell("from pathlib import Path\nimport sys\nROOT = Path.cwd().resolve()\nwhile not (ROOT / 'labs').exists() and ROOT.parent != ROOT:\n    ROOT = ROOT.parent\nsys.path.insert(0, str(ROOT / 'labs'))\nprint(f'Course root: {ROOT}')"),
      nbf.v4.new_markdown_cell("## Implementation\n\nThe reusable lab below deliberately avoids model credentials. It models the boundaries a real provider adapter must respect: trusted policy retrieval, typed output validation, evidence attachment, and safe failure behavior. Replace only the deterministic adapter when experimenting with a model; retain the contract and tests."),
      nbf.v4.new_code_cell(f"import runpy\nrunpy.run_path(str(ROOT / 'labs' / '{lab}'), run_name='__main__')"),
      nbf.v4.new_markdown_cell(f"## Experiment\n\n{exercise}\n\nWrite the expected result before editing code. Then modify a fixture or wrapper and explain whether the behavior should be accepted, retried, escalated, or blocked."),
      nbf.v4.new_markdown_cell("## Production checklist\n\n1. Is the task and allowed evidence explicit?\n2. Is untrusted content marked as data?\n3. Can software validate the output?\n4. Are tool permissions, retries, and budgets enforced outside the model?\n5. Does a representative evaluation set cover normal, ambiguous, and adversarial cases?\n\n## Reflection\n\nWhat does this technique make more reliable than a simpler baseline? What additional complexity does it introduce? Which metric would detect a regression?"),
    ]
    nbf.write(nb, ROOT / "notebooks" / f"{index}.ipynb")
