const source = (doc) => doc.includes("/") ? doc : `docs/${doc}`;
const notebookSource = (notebook) => notebook.includes("/") ? notebook : `notebooks/${notebook}`;

const lesson = (id, level, step, title, summary, outcome, doc, notebook, refs) => ({
  id, level, step, title, summary, outcome, material: source(doc), notebook: notebookSource(notebook), refs,
});

export const lessons = [
  lesson("contracts", "Beginner", 1, "Instruction contracts", "Turn ambiguous requests into observable behavior contracts.", "Specify task, trusted context, constraints, output, and escalation before optimizing wording.", "01-instruction-contracts.md", "01_instruction_contracts.ipynb", ["https://ai.google.dev/gemini-api/docs/prompting-strategies", "https://arxiv.org/abs/2406.06608"]),
  lesson("structured", "Beginner", 2, "Examples and structured outputs", "Use schemas and examples to make model responses dependable interfaces.", "Validate a typed support-case brief and design examples for edge cases.", "02-structured-outputs.md", "02_structured_outputs.ipynb", ["https://platform.openai.com/docs/guides/structured-outputs", "https://docs.pydantic.dev/"]),
  lesson("context", "Beginner", 3, "Context engineering", "Select authoritative evidence instead of filling the context window.", "Rank, delimit, and cite context while preserving abstention for missing evidence.", "03-context-engineering.md", "03_context_engineering.ipynb", ["https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents", "https://arxiv.org/abs/2307.03172"]),
  lesson("tools", "Intermediate", 4, "RAG and tool interfaces", "Build evidence-first retrieval and tool-use contracts.", "Keep tool results as data, validate arguments in code, and handle errors deliberately.", "04-rag-tools.md", "04_rag_and_tools.ipynb", ["https://arxiv.org/abs/2210.03629", "https://platform.openai.com/docs/guides/function-calling"]),
  lesson("multimodal", "Intermediate", 5, "Multimodal prompting", "Extract visible facts from documents with provenance and uncertainty.", "Create an invoice evidence contract that distinguishes observation from inference.", "05-multimodal.md", "05_multimodal_prompting.ipynb", ["https://ai.google.dev/gemini-api/docs/prompting-strategies"]),
  lesson("security", "Intermediate", 6, "Prompt security", "Treat external content as untrusted data and enforce boundaries in code.", "Detect indirect injection and design layered controls for retrieval, tools, and outputs.", "06-prompt-security.md", "06_prompt_security.ipynb", ["https://cheatsheetseries.owasp.org/cheatsheets/LLM_Prompt_Injection_Prevention_Cheat_Sheet.html"]),
  lesson("evals", "Intermediate", 7, "Prompt evaluation", "Turn prompt changes into measurable experiments and release decisions.", "Score a golden set for validity, support, cost, and latency.", "07-evaluation.md", "07_prompt_evaluation.ipynb", ["https://platform.openai.com/docs/guides/evals", "https://arxiv.org/abs/2303.16634"]),
  lesson("agents", "Advanced", 8, "Agentic prompt contracts", "Bound investigative loops, tools, and delegation with explicit policy.", "Choose the least autonomous design that reliably solves the support task.", "08-agentic-prompts.md", "08_agentic_prompts.ipynb", ["https://www.anthropic.com/engineering/building-effective-agents"]),
  lesson("promptops", "Advanced", 9, "PromptOps capstone", "Version, evaluate, release, observe, and roll back model-aware prompts.", "Apply a release gate to a candidate prompt and preserve a safe rollback path.", "09-promptops.md", "09_promptops.ipynb", ["https://www.promptfoo.dev/docs/intro/", "https://arxiv.org/abs/2310.03714"]),
  lesson("technology", "Advanced", 10, "Technology review", "Select libraries by the operational boundary they make safer.", "Compare model APIs, orchestration, retrieval, observability, and evaluation tooling.", "10-technology-review.md", "10_technology_review.ipynb", ["https://langchain-ai.github.io/langgraph/", "https://www.arize.com/docs/phoenix"]),
  lesson("reasoning", "Advanced", 11, "Reasoning techniques", "Use decomposition and verification only when they improve task reliability.", "Design a bounded reasoning and evidence-verification workflow.", "11-reasoning-techniques.md", "11_reasoning_techniques.ipynb", ["https://arxiv.org/abs/2201.11903", "https://arxiv.org/abs/2210.03629"]),
  lesson("coding", "Advanced", 12, "Coding-agent prompting", "Make software changes reviewable, testable, and reversible.", "Write an implementation contract with acceptance criteria and verification evidence.", "12-coding-agent-prompting.md", "12_coding_agent_prompting.ipynb", ["https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot"]),
  lesson("efficiency", "Advanced", 13, "Cost and latency engineering", "Treat quality, cost, and latency as a measured frontier.", "Route and budget requests without silently degrading correctness.", "13-cost-latency-engineering.md", "13_cost_latency_engineering.ipynb", ["https://docs.litellm.ai/", "https://docs.vllm.ai/"]),
  lesson("catalog", "Advanced", 14, "Technique catalog", "Choose techniques based on failure modes, not novelty.", "Map a task to a minimal prompt technique and validation plan.", "14-technique-catalog.md", "14_technique_catalog.ipynb", ["https://arxiv.org/abs/2406.06608"]),
  lesson("playbooks", "Advanced", 15, "Application playbooks", "Apply reusable delivery patterns to common AI-product scenarios.", "Build a support-assistant playbook with escalation and evidence boundaries.", "15-application-playbooks.md", "15_application_playbooks.ipynb", ["https://www.nist.gov/itl/ai-risk-management-framework"]),
  lesson("model-aware", "Advanced", 16, "Model-aware guidance", "Separate stable task intent from model-specific adaptations.", "Create a portable contract and an adaptation layer for a model change.", "16-model-aware-guidance.md", "16_model_aware_guidance.ipynb", ["https://platform.openai.com/docs/guides/prompt-engineering"]),
  lesson("resources", "Advanced", 17, "Resource library", "Build a source map that distinguishes primary evidence from commentary.", "Create an evidence-backed research path for a production decision.", "17-resource-library.md", "17_resource_library.ipynb", ["https://arxiv.org/", "https://huggingface.co/papers"]),
  lesson("behavior", "Beginner", 1, "LLM behavior and prompt anatomy", "Inspect the complete request packet before trying to improve its wording.", "Run controlled experiments on instructions, evidence position, and variation; then diagnose the smallest responsible component.", "curriculum/beginner/01-llm-behavior-and-prompt-anatomy/README.md", "curriculum/beginner/01-llm-behavior-and-prompt-anatomy/llm_behavior_and_prompt_anatomy.ipynb", ["https://arxiv.org/abs/2005.14165", "https://arxiv.org/abs/2307.03172"]),
  lesson("reliability", "Advanced", 19, "Reliability and human-centred AI", "Make uncertainty, review, and recovery visible product features.", "Design a risk-tiered human review and incident recovery path.", "19-reliability-and-human-centred-ai.md", "19_reliability_human_centred_ai.ipynb", ["https://www.nist.gov/itl/ai-risk-management-framework"]),
  lesson("coverage", "Advanced", 20, "Course coverage map", "Connect course skills to a complete production capability map.", "Identify gaps in a proposed system across contracts, context, operations, and governance.", "20-course-coverage-map.md", "20_course_coverage_map.ipynb", ["https://www.nist.gov/itl/ai-risk-management-framework"]),
  lesson("optimization", "Advanced", 21, "Evaluation-driven prompt optimization", "Improve prompts through held-out evidence instead of intuition.", "Run a safe optimization loop with regression gates and rollback.", "21-evaluation-driven-prompt-optimization.md", "21_evaluation_driven_prompt_optimization.ipynb", ["https://dspy.ai/learn/optimization/optimizers/"]),
];

const check = (question, choices, answer, explanation) => ({ question, choices, answer, explanation });

export const checks = {
  contracts: check("Which item belongs in a prompt contract?", ["An observable output and escalation rule", "Production database credentials", "A promise that role text enforces access"], 0, "A contract makes desired behavior observable. Secrets and authorization belong outside the prompt."),
  structured: check("Why validate structured output in application code?", ["To enforce types and reject malformed responses", "To make the model more creative", "To eliminate testing"], 0, "Provider constraints help, but application validation remains the boundary your system controls."),
  context: check("What is best when no approved evidence supports a policy claim?", ["Abstain or escalate", "Invent a likely policy", "Include every available document"], 0, "Grounded systems expose uncertainty instead of producing unsupported answers."),
  tools: check("How should an instruction inside a tool result be treated?", ["As untrusted data", "As a new system instruction", "As automatic approval"], 0, "Tool output does not cross a trust boundary."),
  multimodal: check("What should a system do with an unreadable invoice amount?", ["Flag uncertainty and request review", "Guess from nearby fields", "Issue a refund"], 0, "Visual extraction must distinguish observation from inference."),
  security: check("Which is a defense-in-depth injection control?", ["Least-privilege tools and approval gates", "A longer system prompt only", "Giving retrieved text higher priority"], 0, "Authorization belongs in deterministic policy, not prompt text."),
  evals: check("What makes a prompt comparison credible?", ["Representative cases and pre-defined metrics", "One impressive demo", "Lower token count alone"], 0, "Use normal, ambiguous, and adversarial cases with release metrics."),
  agents: check("When should a deterministic workflow be preferred?", ["When the path is known and reliable", "Whenever multiple tools exist", "Never"], 0, "Use the least autonomous architecture that reliably solves the task."),
  promptops: check("What enables safe recovery after a failed prompt release?", ["Versioned prompts and a rollback path", "Editing production prompts in place", "Removing evaluations"], 0, "PromptOps treats prompts and context policies as evaluated delivery artifacts."),
  technology: check("What should decide a library choice?", ["The operational boundary it makes safer", "The largest marketing claim", "Whether it removes validation"], 0, "Choose tools for specific needs such as state, tracing, retrieval, or evaluation."),
  reasoning: check("What should bound a reasoning workflow?", ["Evidence and stopping criteria", "Unlimited reflection", "A hidden chain of thought request"], 0, "Design observable decompositions and verification without relying on hidden reasoning."),
  coding: check("What is essential before an agent changes code?", ["Acceptance criteria and a verification command", "A vague request to improve it", "Direct access to production"], 0, "A coding task needs a reviewable contract and deterministic verification."),
  efficiency: check("What is a safe cost optimization?", ["Route simple, measured cases to a cheaper path", "Remove all evaluation", "Silently truncate evidence"], 0, "Optimization should preserve quality gates and expose trade-offs."),
  catalog: check("How should a prompting technique be selected?", ["By the failure mode it addresses", "By novelty", "By longest possible prompt"], 0, "Use the smallest technique that solves an observed problem."),
  playbooks: check("What makes an application playbook production-ready?", ["Scenario, controls, metrics, and escalation", "A clever persona only", "A single happy-path demo"], 0, "Playbooks connect user value to operational boundaries."),
  "model-aware": check("What should remain stable across model providers?", ["Task contract and acceptance tests", "Every provider-specific phrasing", "Undocumented behavior"], 0, "Keep intent portable; isolate model adaptations and test them."),
  resources: check("Which source best establishes how a feature works?", ["Primary documentation or a paper", "An uncited social post", "A copied prompt"], 0, "Primary sources make claims auditable and updateable."),
  behavior: check("How should an LLM behavior issue be debugged?", ["Inspect instructions, context, outputs, and evaluation cases", "Add adjectives at random", "Assume temperature is the only cause"], 0, "Behavior emerges from the whole system contract."),
  reliability: check("What is a human-centred response to a high-risk uncertain case?", ["Route it to informed review", "Hide uncertainty", "Force an automated action"], 0, "Risk-tiered review is a reliability mechanism, not merely an interface choice."),
  coverage: check("What does a capability map reveal?", ["Missing controls across the delivery system", "A replacement for evaluation", "A reason to remove documentation"], 0, "Coverage maps help teams find gaps before deployment."),
  optimization: check("What should gate an optimized prompt?", ["Held-out regression and safety checks", "A better-looking single output", "A benchmark it was tuned on only"], 0, "Use a held-out evaluation set and preserve rollback."),
};
