const source = (doc) => doc.includes("/") ? doc : `docs/${doc}`;
const notebookSource = (notebook) => notebook.includes("/") ? notebook : `notebooks/${notebook}`;

const lesson = (id, level, step, title, summary, outcome, doc, notebook, refs) => ({
  id, level, step, title, summary, outcome, material: source(doc), notebook: notebookSource(notebook), refs,
});

export const lessons = [
  lesson("contracts", "Beginner", 2, "Instruction contracts", "Turn ambiguous requests into observable behavior contracts.", "Specify task, trusted context, constraints, output, and escalation before optimizing wording.", "curriculum/beginner/02-instruction-contracts/README.md", "curriculum/beginner/02-instruction-contracts/instruction_contracts.ipynb", ["https://platform.openai.com/docs/guides/prompting", "https://cheatsheetseries.owasp.org/cheatsheets/LLM_Prompt_Injection_Prevention_Cheat_Sheet.html"]),
  lesson("structured", "Beginner", 3, "Constraints, examples, and few-shot learning", "Select examples to clarify a measured decision boundary, not to make prompts longer.", "Compare static, random, similarity, and diversity selection while measuring accuracy and context cost.", "curriculum/beginner/03-constraints-examples-and-few-shot-learning/README.md", "curriculum/beginner/03-constraints-examples-and-few-shot-learning/constraints_examples_few_shot.ipynb", ["https://arxiv.org/abs/2005.14165", "https://arxiv.org/abs/2406.06608"]),
  lesson("context", "Beginner", 4, "Structured outputs and typed interfaces", "Validate model proposals as typed application data, not merely plausible JSON.", "Separate parsing, schema validation, semantic validation, and bounded repair.", "curriculum/beginner/04-structured-outputs-and-typed-interfaces/README.md", "curriculum/beginner/04-structured-outputs-and-typed-interfaces/structured_outputs_and_typed_interfaces.ipynb", ["https://json-schema.org/specification", "https://docs.pydantic.dev/"]),
  lesson("tools", "Beginner", 5, "Prompt patterns and technique selection", "Choose the smallest measured technique for an observed failure.", "Map task, interface, evidence, action, and decomposition failures to a bounded intervention.", "curriculum/beginner/05-prompt-patterns-and-technique-selection/README.md", "curriculum/beginner/05-prompt-patterns-and-technique-selection/prompt_patterns_and_technique_selection.ipynb", ["https://arxiv.org/abs/2406.06608", "https://arxiv.org/abs/2210.03629"]),
  lesson("multimodal", "Intermediate", 12, "Multimodal prompt engineering", "Extract visible facts with provenance, uncertainty, and contradiction handling.", "Distinguish visual observation from inference and escalate conflicting evidence.", "curriculum/intermediate/12-multimodal-prompt-engineering/README.md", "curriculum/intermediate/12-multimodal-prompt-engineering/multimodal_prompt_engineering.ipynb", []),
  lesson("security", "Intermediate", 13, "Prompt security and untrusted content", "Treat external content as untrusted data and enforce boundaries in code.", "Attack a vulnerable design, then retest deterministic controls.", "curriculum/intermediate/13-prompt-security-and-untrusted-content/README.md", "curriculum/intermediate/13-prompt-security-and-untrusted-content/prompt_security_and_untrusted_content.ipynb", ["https://cheatsheetseries.owasp.org/cheatsheets/LLM_Prompt_Injection_Prevention_Cheat_Sheet.html"]),
  lesson("evals", "Intermediate", 7, "Task decomposition and workflow prompting", "Use typed stages when they improve reliability and failure isolation.", "Compare a single request with a bounded sequential workflow.", "curriculum/intermediate/07-task-decomposition-and-workflow-prompting/README.md", "curriculum/intermediate/07-task-decomposition-and-workflow-prompting/task_decomposition_and_workflow_prompting.ipynb", ["https://arxiv.org/abs/2210.03629"]),
  lesson("agents", "Intermediate", 8, "Context engineering", "Select authoritative evidence instead of filling the context window.", "Compare full context with selected, authorized evidence and measure its cost.", "curriculum/intermediate/08-context-engineering/README.md", "curriculum/intermediate/08-context-engineering/context_engineering.ipynb", ["https://arxiv.org/abs/2307.03172"]),
  lesson("promptops", "Intermediate", 9, "Conversation and long-context engineering", "Preserve useful conversation state without treating a larger context window as a solution.", "Compare full history, windows, summaries, and history retrieval.", "curriculum/intermediate/09-conversation-and-long-context-engineering/README.md", "curriculum/intermediate/09-conversation-and-long-context-engineering/conversation_and_long_context_engineering.ipynb", ["https://arxiv.org/abs/2307.03172"]),
  lesson("technology", "Intermediate", 10, "Evidence-grounded prompting and RAG interfaces", "Generate from authorized evidence with provenance, citations, and abstention.", "Compare model-only, unfiltered retrieval, and selected evidence.", "curriculum/intermediate/10-evidence-grounded-prompting-and-rag-interfaces/README.md", "curriculum/intermediate/10-evidence-grounded-prompting-and-rag-interfaces/evidence_grounded_prompting_and_rag_interfaces.ipynb", ["https://arxiv.org/abs/2005.11401"]),
  lesson("reasoning", "Intermediate", 6, "Reasoning-oriented prompting", "Use observable decomposition and verification only when they improve task reliability.", "Compare direct answers with a bounded planner/verifier workflow.", "curriculum/intermediate/06-reasoning-oriented-prompting/README.md", "curriculum/intermediate/06-reasoning-oriented-prompting/reasoning_oriented_prompting.ipynb", ["https://arxiv.org/abs/2201.11903", "https://arxiv.org/abs/2210.03629"]),
  lesson("coding", "Intermediate", 11, "Tool calling and tool interface design", "Design narrow tool contracts and validate proposed arguments.", "Distinguish tool selection from application authorization.", "curriculum/intermediate/11-tool-calling-and-tool-interface-design/README.md", "curriculum/intermediate/11-tool-calling-and-tool-interface-design/tool_calling_and_tool_interface_design.ipynb", ["https://platform.openai.com/docs/guides/function-calling"]),
  lesson("efficiency", "Advanced", 13, "Cost and latency engineering", "Treat quality, cost, and latency as a measured frontier.", "Route and budget requests without silently degrading correctness.", "13-cost-latency-engineering.md", "13_cost_latency_engineering.ipynb", ["https://docs.litellm.ai/", "https://docs.vllm.ai/"]),
  lesson("catalog", "Advanced", 14, "Prompt evaluation", "Turn behavioral changes into measured release decisions.", "Compare baseline and candidate cases, inspect slices, and enforce safety gates.", "curriculum/advanced/14-prompt-evaluation/README.md", "curriculum/advanced/14-prompt-evaluation/prompt_evaluation.ipynb", ["https://platform.openai.com/docs/guides/evals"]),
  lesson("playbooks", "Advanced", 15, "LLM-as-a-judge and human evaluation", "Use judges as measured evaluators, not ground truth.", "Measure agreement and bias; define deterministic and human overrides.", "curriculum/advanced/15-llm-as-a-judge-and-human-evaluation/README.md", "curriculum/advanced/15-llm-as-a-judge-and-human-evaluation/llm_as_a_judge_and_human_evaluation.ipynb", ["https://arxiv.org/abs/2303.16634"]),
  lesson("model-aware", "Advanced", 16, "Evaluation-driven prompt optimization", "Improve behavior through one-variable, held-out evaluation loops.", "Classify failures, compare candidates, and reject safety regressions.", "curriculum/advanced/16-evaluation-driven-prompt-optimization/README.md", "curriculum/advanced/16-evaluation-driven-prompt-optimization/evaluation_driven_prompt_optimization.ipynb", ["https://dspy.ai/learn/optimization/optimizers/"]),
  lesson("resources", "Advanced", 17, "Automatic prompt optimization and DSPy", "Optimize prompts only against a trustworthy held-out evaluation system.", "Compare manual and optimized candidates; detect overfitting.", "curriculum/advanced/17-automatic-prompt-optimization-and-dspy/README.md", "curriculum/advanced/17-automatic-prompt-optimization-and-dspy/automatic_prompt_optimization_and_dspy.ipynb", ["https://dspy.ai/learn/optimization/optimizers/"]),
  lesson("behavior", "Beginner", 1, "LLM behavior and prompt anatomy", "Inspect the complete request packet before trying to improve its wording.", "Run controlled experiments on instructions, evidence position, and variation; then diagnose the smallest responsible component.", "curriculum/beginner/01-llm-behavior-and-prompt-anatomy/README.md", "curriculum/beginner/01-llm-behavior-and-prompt-anatomy/llm_behavior_and_prompt_anatomy.ipynb", ["https://arxiv.org/abs/2005.14165", "https://arxiv.org/abs/2307.03172"]),
  lesson("reliability", "Advanced", 19, "Reliability and human-centred AI", "Make uncertainty, review, and recovery visible product features.", "Design a risk-tiered human review and incident recovery path.", "19-reliability-and-human-centred-ai.md", "19_reliability_human_centred_ai.ipynb", ["https://www.nist.gov/itl/ai-risk-management-framework"]),
  lesson("coverage", "Advanced", 20, "Course coverage map", "Connect course skills to a complete production capability map.", "Identify gaps in a proposed system across contracts, context, operations, and governance.", "20-course-coverage-map.md", "20_course_coverage_map.ipynb", ["https://www.nist.gov/itl/ai-risk-management-framework"]),
  lesson("optimization", "Advanced", 21, "Evaluation-driven prompt optimization", "Improve prompts through held-out evidence instead of intuition.", "Run a safe optimization loop with regression gates and rollback.", "21-evaluation-driven-prompt-optimization.md", "21_evaluation_driven_prompt_optimization.ipynb", ["https://dspy.ai/learn/optimization/optimizers/"]),
];

const check = (question, choices, answer, explanation) => ({ question, choices, answer, explanation });

export const checks = {
  contracts: check("Which item belongs in a prompt contract?", ["An observable output and escalation rule", "Production database credentials", "A promise that role text enforces access"], 0, "A contract makes desired behavior observable. Secrets and authorization belong outside the prompt."),
  structured: check("Why validate structured output in application code?", ["To enforce types and reject malformed responses", "To make the model more creative", "To eliminate testing"], 0, "Provider constraints help, but application validation remains the boundary your system controls."),
  context: check("What is best when no approved evidence supports a policy claim?", ["Abstain or escalate", "Invent a likely policy", "Include every available document"], 0, "Grounded systems expose uncertainty instead of producing unsupported answers."),
  tools: check("How should an instruction inside a tool result be treated?", ["As untrusted data", "As a new system instruction", "As automatic approval"], 0, "Tool output does not cross a trust boundary."),
  multimodal: check("What should a system do with an unreadable invoice amount?", ["Flag uncertainty and request review", "Guess from nearby fields", "Issue a refund"], 0, "Visual extraction must distinguish observation from inference."),
  security: check("Which is a defense-in-depth injection control?", ["Least-privilege tools and approval gates", "A longer system prompt only", "Giving retrieved text higher priority"], 0, "Authorization belongs in deterministic policy, not prompt text."),
  evals: check("What makes a prompt comparison credible?", ["Representative cases and pre-defined metrics", "One impressive demo", "Lower token count alone"], 0, "Use normal, ambiguous, and adversarial cases with release metrics."),
  agents: check("When should a deterministic workflow be preferred?", ["When the path is known and reliable", "Whenever multiple tools exist", "Never"], 0, "Use the least autonomous architecture that reliably solves the task."),
  promptops: check("What enables safe recovery after a failed prompt release?", ["Versioned prompts and a rollback path", "Editing production prompts in place", "Removing evaluations"], 0, "PromptOps treats prompts and context policies as evaluated delivery artifacts."),
  technology: check("What should decide a library choice?", ["The operational boundary it makes safer", "The largest marketing claim", "Whether it removes validation"], 0, "Choose tools for specific needs such as state, tracing, retrieval, or evaluation."),
  reasoning: check("What should bound a reasoning workflow?", ["Evidence and stopping criteria", "Unlimited reflection", "A hidden chain of thought request"], 0, "Design observable decompositions and verification without relying on hidden reasoning."),
  coding: check("What is essential before an agent changes code?", ["Acceptance criteria and a verification command", "A vague request to improve it", "Direct access to production"], 0, "A coding task needs a reviewable contract and deterministic verification."),
  efficiency: check("What is a safe cost optimization?", ["Route simple, measured cases to a cheaper path", "Remove all evaluation", "Silently truncate evidence"], 0, "Optimization should preserve quality gates and expose trade-offs."),
  catalog: check("How should a prompting technique be selected?", ["By the failure mode it addresses", "By novelty", "By longest possible prompt"], 0, "Use the smallest technique that solves an observed problem."),
  playbooks: check("What makes an application playbook production-ready?", ["Scenario, controls, metrics, and escalation", "A clever persona only", "A single happy-path demo"], 0, "Playbooks connect user value to operational boundaries."),
  "model-aware": check("What should remain stable across model providers?", ["Task contract and acceptance tests", "Every provider-specific phrasing", "Undocumented behavior"], 0, "Keep intent portable; isolate model adaptations and test them."),
  resources: check("Which source best establishes how a feature works?", ["Primary documentation or a paper", "An uncited social post", "A copied prompt"], 0, "Primary sources make claims auditable and updateable."),
  behavior: check("How should an LLM behavior issue be debugged?", ["Inspect instructions, context, outputs, and evaluation cases", "Add adjectives at random", "Assume temperature is the only cause"], 0, "Behavior emerges from the whole system contract."),
  reliability: check("What is a human-centred response to a high-risk uncertain case?", ["Route it to informed review", "Hide uncertainty", "Force an automated action"], 0, "Risk-tiered review is a reliability mechanism, not merely an interface choice."),
  coverage: check("What does a capability map reveal?", ["Missing controls across the delivery system", "A replacement for evaluation", "A reason to remove documentation"], 0, "Coverage maps help teams find gaps before deployment."),
  optimization: check("What should gate an optimized prompt?", ["Held-out regression and safety checks", "A better-looking single output", "A benchmark it was tuned on only"], 0, "Use a held-out evaluation set and preserve rollback."),
};
